# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CopyStyle
                                 A QGIS plugin
 Verschiedene Tools
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-26
        copyright            : (C) 2026 by Kevin Landolt
        email                : qgis@klandolt.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load CopyStyle class from file CopyStyle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CopyStyle import CopyStyle
    return CopyStyle(iface)
